# Hot-reloading with Air - https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
exclude_dir = ["cypress", "docker", "tmp", "web/static", "node_modules", "json-server"]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ."
bin = "tmp/main"
full_bin = "pkill -9 'dlv|main'; sleep 0.1; dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 ./tmp/main"
include_ext = ["go", "gotmpl"]
