version: "3.6"

services:
  deputy-hub:
    platform: linux/amd64
    image: deputy-hub:dev-latest
    build:
      target: dev
    ports:
      - '2345:2345'
      - 8888:8888
    volumes:
      - .:/app:rw,delegated
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080

  yarn:
    command: watch

  json-server:
    volumes:
      - ./json-server/config:/app/config
