version: "3.6"

volumes:
  # prevents the local built assets interfering with the docker build
  static:

services:
  deputy-hub:
    build:
      context: ..
      dockerfile: ./docker/sirius-deputy-hub/Dockerfile
      target: dev
    ports:
      - '2345:2345'
      - '8888:1234'
    volumes:
      - ..:/app:rw,delegated
      - static:/app/web/static
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      PREFIX: /supervision/deputies/public-authority

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'
