version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/sirius-deputy-hub/Dockerfile
    ports: ["8888:8080"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'

  puppeteer:
    build: ./puppeteer
    depends_on:
      - app
      - json-server
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-supervision-deputy-hub
      - LHCI_GITHUB_APP_TOKEN

  cypress:
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    command: ["--headless", "-b", "chrome"]
    depends_on:
      - app
      - json-server