version: "3.6"

services:
  deputy-hub:
    image: sirius-deputy-hub:latest
    build:
      context: ..
      dockerfile: ./docker/sirius-deputy-hub/Dockerfile
    ports: ["8888:1234"]
    environment:
      PORT: 8888
      SIRIUS_URL: http://json-server:3000
      PREFIX: /supervision/deputies/public-authority

  json-server:
    image: deputy-hub-json-server:latest
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    ports:
      - '3000:3000'

  puppeteer:
    image: deputy-hub-puppeter:latest
    build: ./puppeteer
    depends_on:
      - deputy-hub
      - json-server
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-supervision-deputy-hub
      - LHCI_GITHUB_APP_TOKEN

  cypress:
    image: deputy-hub-cypress:latest
    build:
      context: ..
      dockerfile: ./docker/cypress/Dockerfile
    volumes:
      - ../test-results:/test-results
    command: ["--headless", "-b", "chrome"]
    depends_on:
      - deputy-hub
      - json-server
