version: "3.6"

services:
  deputy-hub:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/sirius-deputy-hub/Dockerfile
      target: dev
    ports:
      - '2345:2345'
      - '8888:1234'
    volumes:
      - ..:/app:rw,delegated
      - /app/web/static
    environment:
      SIRIUS_URL: http://json-server:3000
      SIRIUS_PUBLIC_URL: http://localhost:8080
      FIRM_HUB_HOST: http://localhost:8887
      PREFIX: /supervision/deputies
      FEATURES: assurance_visits

  json-server:
    build:
      context: ..
      dockerfile: ./docker/json-server/Dockerfile
    volumes:
      - ../json-server/db:/app/db
    ports:
      - '3000:3000'
